# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c7585c82ad219462efef20786fc51309bf1eb692a8d53fadce9315269bd0bcd22a02d0fe0de6378a7908a8e9bedc2e5cd7acc48f1d489c5484441d472ae4195

test:
  secret_key_base: 4b6df5215a552d7f9c43ab716a11748da89cc76b0924720e46c41c93d15d96a84f5cb6a456149d5bdabec4fe93830f05e5a5aba9bdc85f22d535302744f5f782

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
